### ISSUE TITLE
Pip issue

### ISSUE THREAD

**Issue by andreabac3** [nalepae/pierogi#1]
Hello @nalepae 
It is the first time that I try your library, however I have encountered a problem with pip installation.

I am currently on manjaro linux 20 and have installed your library as indicated by doing
`pip3 install pierogi --user`
when i try to import the library as shown in the examples in the readme i get this error
`from pierogi.pierogi import Pierogi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$HOME/.local/lib/python3.7/site-packages/pierogi/pierogi.py", line 1, in <module>
    from .utils.websocket import WebSocketServer as _WebSocketServer
  File "$HOME/.local/lib/python3.7/site-packages/pierogi/utils/websocket.py", line 4, in <module>
    import websockets as _websockets
ModuleNotFoundError: No module named 'websockets'
`

**Comment by andreabac3** [comment]
Sorry for the issue, the problem is on my side for an env problem!
